
# overlays/prod/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
- path: replica_count_prod.yaml
commonLabels:
  env: production  # Label applied to every resource
namePrefix: prod-  # Prefix added to the name of all resources
